<a href="https://colab.research.google.com/github/venkisamarth/advanced-ML/blob/main/ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import pandas as pd


In [43]:
df=pd.read_csv("customer.csv")


In [44]:
df.sample(5)

age  gender review education purchased
45   61    Male   Poor        PG       Yes
49   25  Female   Good        UG        No
39   76    Male   Poor        PG        No
47   38  Female   Good        PG       Yes
46   64  Female   Poor        PG        No

In [45]:
df=df.iloc[:,2:]

In [46]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [47]:
from sklearn.preprocessing  import OrdinalEncoder

In [48]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:2],df.iloc[:,-1],random_state=1)

In [49]:
x_train

review education
36     Good        UG
19     Poor        PG
42     Good        PG
49     Good        UG
26     Poor        PG
22     Poor        PG
13  Average    School
41     Good        PG
17     Poor        UG
45     Poor        PG
24  Average        PG
23     Good    School
4   Average        UG
33     Good        PG
14     Poor        PG
30  Average        UG
10     Good        UG
28     Poor    School
44  Average        UG
34  Average    School
18     Good    School
20  Average    School
25     Good    School
6      Good    School
7      Poor    School
47     Good        PG
1      Poor        UG
16     Poor        UG
0   Average    School
15     Poor        UG
5   Average    School
11     Good        UG
9      Good        UG
8   Average        UG
12     Poor    School
43     Poor        PG
37  Average        PG

In [50]:
df["review"].value_counts()
df.isnull()

review  education  purchased
0    False      False      False
1    False      False      False
2    False      False      False
3    False      False      False
4    False      False      False
5    False      False      False
6    False      False      False
7    False      False      False
8    False      False      False
9    False      False      False
10   False      False      False
11   False      False      False
12   False      False      False
13   False      False      False
14   False      False      False
15   False      False      False
16   False      False      False
17   False      False      False
18   False      False      False
19   False      False      False
20   False      False      False
21   False      False      False
22   False      False      False
23   False      False      False
24   False      False      False
25   False      False      False
26   False      False      False
27   False      False      False
28   False      False      False
29   False      False      False
30   False      False      False
31   False      False      False
32   False      False      False
33   False      False      False
34   False      False      False
35   False      False      False
36   False      False      False
37   False      False      False
38   False      False      False
39   False      False      False
40   False      False      False
41   False      False      False
42   False      False      False
43   False      False      False
44   False      False      False
45   False      False      False
46   False      False      False
47   False      False      False
48   False      False      False
49   False      False      False

In [51]:
y_train

36    Yes
19    Yes
42    Yes
49     No
26     No
22    Yes
13     No
41    Yes
17    Yes
45    Yes
24    Yes
23     No
4      No
33    Yes
14    Yes
30     No
10    Yes
28     No
44     No
34     No
18     No
20    Yes
25     No
6      No
7     Yes
47    Yes
1      No
16    Yes
0      No
15     No
5     Yes
11    Yes
9     Yes
8      No
12     No
43     No
37    Yes
Name: purchased, dtype: object

In [52]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [53]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [54]:
x_train=oe.transform(x_train)

In [55]:
x_train

array([[2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 2.]])

In [56]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [57]:
x_train

array([[2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 2.]])

In [58]:
from sklearn.preprocessing import LabelEncoder

In [59]:
le=LabelEncoder()

In [75]:
le.fit(y_train)
le.fit(y_test)

LabelEncoder()

In [72]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [77]:
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [78]:
df["purchased"].value_counts()

No     26
Yes    24
Name: purchased, dtype: int64

In [79]:
y_train

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1])